CREATE TABLE `#__myextension_foobars` (
    `id` INTEGER UNSIGNED NOT NULL DEFAULT NULL AUTO_INCREMENT,
    `content` TEXT  NOT NULL DEFAULT '',
    `checked_out` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `checked_out_time` DATETIME  NOT NULL DEFAULT '0000-00-00 00:00:00',
    `params` TEXT  NOT NULL DEFAULT '',
    `ordering` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `hits` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `published` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY(`id`)
) CHARACTER SET `utf8` COLLATE `utf8_general_ci`;